FROM ubuntu:14.04
MAINTAINER Dinesh Weerapurage "xydinesh@gmail.com"
# set an environment variable with ENV
ENV REFRESHED_AT 2014-07-22
RUN apt-get -qq update

# add your custom commads here
RUN apt-get install -y r-base r-base-dev

